Start stop watch implemented
anthonyrodarte/stop-watch pull request #5
Opened 2018-02-27 21:40 UTC by anthonyrodarte

2018-02-27 21:52 UTC, ghost requested changes

2018-02-27 21:52 UTC, occs commented on stopwatch/main.js
> +  i = setInterval(count, 1000)
You don't use `i`. Also, if you want to declare a variable you use `var`.

2018-02-27 21:52 UTC, occs commented on stopwatch/main.js
> +  sec++
Don't abbreviate variable names.

2018-02-27 21:52 UTC, occs commented on stopwatch/main.js
> +  if (sec == 60) {
Always use strict equality `===`.

2018-02-27 21:52 UTC, occs commented on stopwatch/main.js
> +function count() {
The function `count` should take some parameters.

2018-02-27 21:52 UTC, occs commented on stopwatch/main.js
> +var sec = 0, min = 0, hour = 0
Consider grouping these in an object to make them easier to pass into other functions.

2018-02-27 21:52 UTC, occs commented on stopwatch/main.js
> +  time.textContent = hour + ':' + min + ':' + sec
Return the time string and use it to set the time.textContent in another part of the code.

2018-02-27 21:54 UTC, miladmemarian approved these changes

2018-02-28 00:25 UTC, ghost approved these changes

2018-02-28 00:27 UTC, merged